### ISSUE TITLE
Please give us an option to remove the text at the topright of the screen 

### ISSUE THREAD

**Issue by elrandir** [PunishXIV/YesAlready#111]
I don't really find the new toggle useful, and thus I really don't need the visual clutter of YesAlready: on/off always visible on my screen. Please give us an option to hide the text, thank you.

**Comment by Haselnussbomber** [comment]
You can disable it in the Dalamud Settings under the Server Info Bar tab. 🙂

**Comment by kawaii** [comment]
We're going to see if we can reflect the server info bar setting specifically into YesAlready so the same option is not essentially controlled in 2 different places by 2 different settings.

**Comment by elrandir** [comment]
Thank you! Didn't know you could control it there <3
