### ISSUE TITLE
New yes already feature. no way to get rid of.

### ISSUE THREAD

**Issue by Xehanort09** [PunishXIV/YesAlready#113]
I don't want the YesAlready: On on my top right screen already with five other things. I don't see a way to turn that off.

**Comment by smolfluffycat** [comment]
Came here to say the same thing, glad it is already posted as this new "feature" is incredibly annoying.

**Comment by Dainina** [comment]
> I don't want the YesAlready: On on my top right screen already with five other things. I don't see a way to turn that off.



> Came here to say the same thing, glad it is already posted as this new "feature" is incredibly annoying.

You can turn this on or off in the normal Dalamud settings. There's a tab for server bar.

Tell me you've never looked at the settings without telling me you've never looked at the settings ¯_(ツ)_/¯.

**Comment by kawaii** [comment]
I pushed an update to latest just now that mirrors the core Dalamud DTR/server info bar settings into a tab in the plugin itself.
