### ISSUE TITLE
Auto OK after death in Dungeon / Raid

### ISSUE THREAD

**Issue by baelrayneVessdren** [PunishXIV/YesAlready#122]
Hi. 

Dying while YA is active causes the addon to auto-accept the resurrect prompt. At first it did not behave like that. Happened suddenly. No dialog / regex entries to cause behavior. Also nothing under the Bothers section that states to auto accept death confirmation. AutoGimmick is disabled as well.

![image](https://github.com/PunishXIV/YesAlready/assets/131447339/3f1ba779-ffe8-49df-8eda-94ed208a401d)

![image](https://github.com/PunishXIV/YesAlready/assets/131447339/5def693d-5e8b-43da-8e16-5e7ef3e81471)

![image](https://github.com/PunishXIV/YesAlready/assets/131447339/6e732ae6-d18c-475a-a6a3-12eddf29d33f)

Maybe one of my settings is wrong? Appreciate the help, otherwise thanks for fixing it in advance.

BR

**Comment by Jaksuhn** [comment]
You'll have to disable your `YesNo`s one by one and see which it is. There is no bother dedicated to that nor is it a gimmick

**Comment by baelrayneVessdren** [comment]
Thanks a lot for that information. Will do that and get back here. Might be something so general, that others won't have to walk into it.

**Comment by Jaksuhn** [comment]
>  identify the /Enter as the beginning of the string.

You can do that with the `^` character to match the beginning or the `$` character to match the end

**Comment by baelrayneVessdren** [comment]
Thanks for the suggestion and I would probably not have figured it out (or much later) without you. So if I understand you correctly the syntax should look like this /^Enter.*?/ ?
