### ISSUE TITLE
Feature request: Datacenter travel confirmation

### ISSUE THREAD

**Issue by spectral54** [PunishXIV/YesAlready#126]
DC Travel has one pointless dialog (the first one, explaining what it is), and one really annoying dialog at the end, after several seconds of lag.

The one at the end always trips me up. I think it's actually going to start doing the data center travel and that takes time, so I go get something to drink or whatever. I come back, and it's still sitting there waiting for me to confirm.

It'd be great if YesAlready could skip these two dialogs. Even better if it only skipped the second one if the estimated travel time was less than some configurable threshold (or maybe only if it's "less than 1 minute" to start with).

I think this can be done by looking for LobbyDKTCheck and LobbyDKTCheckExec(but only if the right string for estimated travel time is present).

**Comment by Jaksuhn** [comment]
you'd probably be interested in [lifestream](https://github.com/NightmareXIV/Lifestream)

**Comment by Jaksuhn** [comment]
it'll be in `1.7.0.9`
