### ISSUE TITLE
SalvageDialog (Bulk) enabled causes crashes

### ISSUE THREAD

**Issue by LTS-FFXIV** [PunishXIV/YesAlready#127]
title

**Comment by Jaksuhn** [comment]
Please try testing `1.7.0.5`

**Comment by LTS-FFXIV** [comment]
Tested on 1.7.0.7, still causes crashes on desynth of any non-crafted item

**Comment by JustForFF** [comment]
Confirming that this is the case for me too, unchecked it works perfectly fine

**Comment by Jaksuhn** [comment]
I'm disabling it until simple tweaks is back so I can get a better debugger
