### ISSUE TITLE
FashonCheck interacts with timers menu

### ISSUE THREAD

**Issue by Ivinedra** [PunishXIV/YesAlready#128]
The "FashionCheck" bothers setting effect the Fashion Report details screen that is displayed when clicking the Fashion Report entry in the timer menu.
![image](https://github.com/PunishXIV/YesAlready/assets/58122205/ae935cbf-ae03-441e-b532-7e36c1e17e45)

**Comment by Jaksuhn** [comment]
will be fixed in `1.7.0.9`
