### ISSUE TITLE
Zone restriction in french doesn't work anymore

### ISSUE THREAD

**Issue by KarlitosVII** [PunishXIV/YesAlready#133]
Hello,
Since a recent update I have to use the english name of the zone I want to restrict. I have a lot of entries (all Inns, Mor Dhona, Ishgard, Ultima Thulé, etc.) so I wouldn't want to update them all.

Thank you. :)

**Comment by Jaksuhn** [comment]
What language does it show in the zonelist window? I don't think tha'ts been touched at all

**Comment by KarlitosVII** [comment]
Nevermind, today it works. It seems that some time it fails to load french data for whatever reason.
Thanks anyway.
