### ISSUE TITLE
Can't add "Restore item" on Glamour Outfits

### ISSUE THREAD

**Issue by KyonKyonxox** [PunishXIV/YesAlready#138]
**Version: YesAlready V1.9.0.0**

![Screenshot_77](https://github.com/user-attachments/assets/d4deae5a-c143-4ea8-9667-2981f3267c59)
![Screenshot_76](https://github.com/user-attachments/assets/524f876f-1401-498e-bb59-3f2f69680139)

**Scenario 1 - Manually add the prompt to YesNo**
Open YesAlready via /pyes text command
YesNo tab
Plus for "add new entry"
Several variations of partial text were attempted. All ended in failure.
"Together, these items form an outfit glamour"
Tried it on its own, as part of a RegEx, tried partial text from further in the message, nothing.

**Scenario 2 - Use the "last" option with text command**
Convert a Glamour Outfit back into its actual items
Confirm the dialogue
attempted "/pyes last"
attempted "yesalready last"
Both added the entry "Restore item to its original form?" which is the prompt for restoring simple items, not Glamour Outfits. I assume it fetched it because I did that several times before moving to Outfits.
Using "lastlist" and "lasttalk" similarly gave me the prompts for the NPC I spoke to to enter the inn room in Tuliyollal.

**Comment by Jaksuhn** [comment]
That addon isn't `SelectYesno`, it's `MiragePrismPrismSetConvertC`. You would have to add it as a custom bother
