### ISSUE TITLE
Feature Request: Hold to auto-skip

### ISSUE THREAD

**Issue by SmoothJaz** [PunishXIV/YesAlready#91]
having to add names for each character is fine till its an NPC that repeatedly shows up in quests and dialogues you dont want to skip for the first time

in those cases having a button to auto-skip similar to the "always yes" hold function would be nice to have. it could even be bundled into the "always yes" command to be honest since those two usually go hand in hand anyway

**Comment by Jaksuhn** [comment]
added v1.6.2.0
