### ISSUE TITLE
Feature Request: Aetherial Reduction

### ISSUE THREAD

**Issue by pincoide** [PunishXIV/YesAlready#92]
Would it be possible to add Aetherial Reduction to the bothers so it clicks them all automatically (so we don't have to do a million clicks every time)?
This should be part of the game tbh (there is no reason to not reduce a listed item), but since is not maybe you can do it 🤣

**Comment by Zyian** [comment]
This probably isn't needed anymore, since it **is** in the game now as of 6.5 patch with automatic Reduction

**Comment by pincoide** [comment]
Yeah when I sent this request I sent the same to the game devs, they managed to do it first so we can close this 😄
