### ISSUE TITLE
Blank entires being added to Talk tab if no target is selected

### ISSUE THREAD

**Issue by keoShine** [PunishXIV/YesAlready#95]
If the "Add current target as new entry" button on the Talk tab of the config window is pressed without a target, an entry with an empty string for the name is added.. The blank entries can't be interacted with to remove them except through manually editing the Config file and cause a blank line to be drawn on the node list (screenshot below).. Potentially could be fixed by adding a check that targetName is not an empty string before adding it as a new Talk entry..

![image](https://user-images.githubusercontent.com/32491958/225160631-d852a4ff-0fb5-4a12-8d41-370eca776df8.png)

**Comment by Jaksuhn** [comment]
added v1.6.2.0
