### ISSUE TITLE
Feature Request: Entrust Duplicates

### ISSUE THREAD

**Issue by cheeserole** [PunishXIV/YesAlready#97]
When clicking "Entrust Duplicates" on your retainer inventory, you have to confirm what duplicates to entrust and then manually click "Close Window."

I'd appreciate if we could skip the whole process, or at least let it automatically click "Close Window". I see that in the help text under YesNo there is the text:
> Currently supported text addons:
> - SelectYesNo

Could we add "SelectCloseWindow" to that or no?

**Comment by Jaksuhn** [comment]
both `RetainerItemTransferList` and `RetainerItemTransferProgress` are in now
